name: podipu
description: A Simple Podcast App.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  google_fonts: ^5.1.0
  get_it: ^7.6.4
  cached_network_image: ^3.3.0
  palette_generator: ^0.3.3+3
  just_audio: ^0.9.35
  audio_session: ^0.1.16
  rxdart: ^0.27.7
  # flutter_seekbar: ^1.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0
  persistent_bottom_nav_bar: ^5.0.2
  http: ^1.1.0
  intl: ^0.18.1
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    
